package dto

type User struct {
	UserName string `json:"user_name"`
	PassWord string `json:"password"`
}

type AutoGenerated struct {
	ErrNo   int    `json:"err_no"`
	ErrMsg  string `json:"err_msg"`
	Results struct {
		Number int    `json:"number"`
		Token  string `json:"token"`
		WsURL  string `json:"ws_url"`
	} `json:"results"`
}
