mode: debug
port: 7777

logger:
  loglevel: debug
  logdir: /opt/log
  logfilename: init.log
  logformat: text

kafka:
  addresses: ["127.0.0.1:9092"]
  consumergroupid: test
  consumeroffsetsinitial: newest
